# Generated by Django 5.1.3 on 2024-12-11 16:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Authors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=40, verbose_name='ФИО пассажира')),
                ('birth_date', models.IntegerField(verbose_name='Дата рождения')),
                ('country_citizen', models.CharField(max_length=100, verbose_name='Страна проживания')),
            ],
        ),
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='название книги')),
                ('genre', models.CharField(max_length=40, verbose_name='жанр')),
                ('year', models.IntegerField(verbose_name='год написания')),
                ('author_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.authors', verbose_name='id автора')),
            ],
        ),
    ]
